from core.menu import (
    show_main_menu, get_main_choice,
    show_symmetric_menu, show_asymmetric_menu, show_hash_menu,
    get_sub_choice
)
from core.input_handler import get_action, get_text_input, get_key_input, ask_generate_key

def handle_symmetric():
    while True:
        show_symmetric_menu()
        algo_choice = get_sub_choice()

        if algo_choice == "0":
            break
        elif algo_choice not in {"1", "2", "3"}:
            print("Invalid choice. Please try again.")
            continue

        while True:
            action = get_action()

            if action == "0":
                break
            elif action == "1":
                plaintext = get_text_input("Enter plaintext")
                use_auto_key = ask_generate_key()
                if use_auto_key:
                    print("Random key will be generated by algorithm module.")
                else:
                    key = get_key_input()
                    print(f"Manual key entered: {key}")
                print("Encryption flow prepared.")
            elif action == "2":
                ciphertext = get_text_input("Enter ciphertext")
                key = get_key_input()
                print(f"Ciphertext: {ciphertext}")
                print(f"Key: {key}")
                print("Decryption flow prepared.")
            else:
                print("Invalid action. Please try again.")



def handle_asymmetric():
    while True:
        show_asymmetric_menu()
        choice = get_sub_choice()
        if choice == "1":
            print("RSA selected.")
        elif choice == "0":
            break
        else:
            print("Invalid choice. Please try again.")



def main():
    while True:
        show_main_menu()
        choice = get_main_choice()

        if choice == "1":
            handle_symmetric()
        elif choice == "2":
            handle_asymmetric()
        elif choice == "3":
            handle_hash()
        elif choice == "0":
            print("Exiting program...")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()